In [1]:

#Mounting  drive
#else  perform manually through the files tab

from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [2]:
#Import package
import pandas as pd
import numpy as np

In [3]:
path = '/content/drive/MyDrive/IMDBproject/imdb_data (1).csv'
imdb_df = pd.read_csv(path)

In [4]:
imdb_df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970

In [5]:
imdb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     3000 non-null   int64
 1   belongs_to_collection  604 non-null    object
 2   budget                 3000 non-null   int64
 3   genres                 2993 non-null   object
 4   homepage               946 non-null    object
 5   imdb_id                3000 non-null   object
 6   original_language      3000 non-null   object
 7   original_title         3000 non-null   object
 8   overview               2992 non-null   object
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object
 11  production_companies   2844 non-null   object
 12  production_countries   2945 non-null   object
 13  release_date           3000 non-null   object
 14  runtime                2998 non-null   float64
 15  spoken_languages       2980 non-null   object
 16  status                 3000 non-null   object
 17  tagline                2403 non-null   object
 18  title                  3000 non-null   object
 19  Keywords               2724 non-null   object
 20  cast                   2987 non-null   object
 21  crew                   2984 non-null   object
 22  revenue                3000 non-null   int64
dtypes: float64(2), int64(3), object(18)
memory usage: 539.2+ KB

In [6]:
print(imdb_df.columns)

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

In [14]:
type(imdb_df.loc[0,'crew'])

str

In [17]:
#eval
crew_list = eval(imdb_df.loc[0,'crew'])
len(crew_list)

72

In [16]:
type(crew_list)

list

In [18]:
#converting string values to proper lists for 3 columns
#generes cast and crew

#creating function

def convert_string_to_list(str):
  return eval(str)

In [21]:
#Apply above fnction to 3 cloumns : genres,cast,crew
imdb_df['genre']=imdb_df['genres'].apply(convert_string_to_list)
imdb_df['cast']=imdb_df['cast'].apply(convert_string_to_list)
imdb_df['crew']=imdb_df['crew'].apply(convert_string_to_list)

#due to null values causing issue
#error :  TypeError: eval() arg 1 must be a string, bytes or code object

# 3   genres   2993 non-null   object
#7 null values

TypeError: eval() arg 1 must be a string, bytes or code object

In [22]:
imdb_df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

In [23]:
columns_to_keep =['budget','genres','imdb_id','original_language', 'original_title','revenue','cast','crew']

In [24]:
imdb_df = imdb_df[columns_to_keep]

In [25]:
imdb_df.columns

Index(['budget', 'genres', 'imdb_id', 'original_language', 'original_title',
       'revenue', 'cast', 'crew'],
      dtype='object')

In [26]:
imdb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   budget             3000 non-null   int64
 1   genres             2993 non-null   object
 2   imdb_id            3000 non-null   object
 3   original_language  3000 non-null   object
 4   original_title     3000 non-null   object
 5   revenue            3000 non-null   int64
 6   cast               2987 non-null   object
 7   crew               2984 non-null   object
dtypes: int64(2), object(6)
memory usage: 187.6+ KB

In [27]:
#drop the null values/observations
imdb_nonull_df = imdb_df.dropna()

In [28]:
imdb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   budget             3000 non-null   int64
 1   genres             2993 non-null   object
 2   imdb_id            3000 non-null   object
 3   original_language  3000 non-null   object
 4   original_title     3000 non-null   object
 5   revenue            3000 non-null   int64
 6   cast               2987 non-null   object
 7   crew               2984 non-null   object
dtypes: int64(2), object(6)
memory usage: 187.6+ KB

1 imdb_df['crew'].isna()
- Checks which rows in the crew column are NaN (null/missing).
- Returns a boolean Series (True for null, False for non-null).

2 ~imdb_df['crew'].isna()
- The ~ operator flips the boolean values.
- So now it’s True for non-null values and False for null values.
- This ensures we only target rows where crew is not null.

3 imdb_df.loc[condition, 'crew']
- .loc is used for label-based indexing.
- Here, it selects only the rows where crew is non-null, and specifically the crew column.

4 .apply(convert_to_list)
- Applies the function convert_to_list to each non-null value in the crew column.
- Example: if crew contains a string like "John, Mary", your function might turn it into ["John", "Mary"].

5 Assignment (=)
- The transformed values are reassigned back into the same crew column, but only for the non-null rows.
- Null values remain untouched.

In [30]:
#apply the above function only on non null values in genres column
imdb_df.loc[~imdb_df['genres'].isna(),'genres']= imdb_df.loc[~imdb_df['genres'].isna(),'genres'].apply(convert_string_to_list)

In [31]:
#apply the above function only on non null values in cast column
imdb_df.loc[~imdb_df['cast'].isna(),'cast']= imdb_df.loc[~imdb_df['cast'].isna(),'cast'].apply(convert_string_to_list)

In [32]:
#apply the above function only on non null values in crew column
imdb_df.loc[~imdb_df['crew'].isna(),'crew']= imdb_df.loc[~imdb_df['crew'].isna(),'crew'].apply(convert_string_to_list)

In [39]:
imdb_df.loc[2,'genres']

[{'id': 18, 'name': 'Drama'}]

In [40]:
#creating  a copy of imdb_df
imdb_df_new = imdb_df.copy()

# 1. Which movie made the highest profit? Who were its producer and director? Identify the actors in that film.

In [43]:
imdb_df_new.describe()

             budget       revenue
count  3.000000e+03  3.000000e+03
mean   2.253133e+07  6.672585e+07
std    3.702609e+07  1.375323e+08
min    0.000000e+00  1.000000e+00
25%    0.000000e+00  2.379808e+06
50%    8.000000e+06  1.680707e+07
75%    2.900000e+07  6.891920e+07
max    3.800000e+08  1.519558e+09

In [46]:
#Replace extremely low values of budget and revenue column with median values of budget, revenue
imdb_df_new.loc[imdb_df_new['budget']<1000,'budget']= imdb_df_new['budget'].median()

imdb_df_new.loc[imdb_df_new['revenue']<1000,'revenue']= imdb_df_new['revenue'].median()

In [47]:
imdb_df_new.describe()

/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:4779: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)

             budget       revenue        profit          roi
count  3.000000e+03  3.000000e+03  3.000000e+03  3000.000000
mean   2.474467e+07  6.704518e+07  4.419452e+07          inf
std    3.583254e+07  1.373964e+08  1.123274e+08          NaN
min    2.500000e+03  1.404000e+03 -1.074474e+08   -99.999948
25%    8.000000e+06  2.947600e+06  1.795200e+04    17.176318
50%    8.000000e+06  1.680873e+07  6.121122e+06   239.984076
75%    2.900000e+07  6.891920e+07  4.143293e+07          NaN
max    3.800000e+08  1.519558e+09  1.316249e+09          inf

In [48]:
#create profit and ROI column
imdb_df_new['profit'] = imdb_df_new['revenue'] - imdb_df_new['budget']
imdb_df_new['roi']= 100* (imdb_df_new['profit']/imdb_df_new['budget'])

In [49]:
imdb_df_new.head()

,budget,genres,imdb_id,original_language,original_title,revenue,cast,crew,profit,roi
0,14000000,"[{'id': 35, 'name': 'Comedy'}]",tt2637294,en,Hot Tub Time Machine 2,12314651,"[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",-1685349,-12.038207
1,40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",tt0368933,en,The Princess Diaries 2: Royal Engagement,95149435,"[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",55149435,137.873588
2,3300000,"[{'id': 18, 'name': 'Drama'}]",tt2582802,en,Whiplash,13092000,"[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",9792000,296.727273
3,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",tt1821480,hi,Kahaani,16000000,"[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",14800000,1233.333333
4,8000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",tt1380152,ko,마린보이,3923970,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",-4076030,-50.950375

In [50]:
#calculate max profit
imdb_df_new['profit'].max()

1316249360

In [52]:
#movie that has the maximum profit
imdb_df_new[imdb_df_new['profit']==imdb_df_new['profit'].max()]

,budget,genres,imdb_id,original_language,original_title,revenue,cast,crew,profit,roi
1761,190000000,"[{'id': 28, 'name': 'Action'}]",tt2820852,en,Furious 7,1506249360,"[{'cast_id': 17, 'character': 'Dominic Toretto...","[{'credit_id': '52fe4cc8c3a36847f823e681', 'de...",1316249360,692.762821

In [54]:
max_profit_movie_df = imdb_df_new.iloc[imdb_df_new['profit'].idxmax()]

In [55]:
max_profit_movie_df.head()

budget                                    190000000
genres               [{'id': 28, 'name': 'Action'}]
imdb_id                                   tt2820852
original_language                                en
original_title                            Furious 7
Name: 1761, dtype: object

In [56]:
max_profit_movie_df.loc['cast'][0]['name']

'Vin Diesel'

In [57]:
#Need to find the director and  producer from the forst question
crew_list= max_profit_movie_df.loc['crew']
crew_list[0:3]

[{'credit_id': '52fe4cc8c3a36847f823e681',
  'department': 'Production',
  'gender': 2,
  'id': 12835,
  'job': 'Producer',
  'name': 'Vin Diesel',
  'profile_path': '/7rwSXluNWZAluYMOEWBxkPmckES.jpg'},
 {'credit_id': '52fe4cc8c3a36847f823e687',
  'department': 'Production',
  'gender': 2,
  'id': 11874,
  'job': 'Producer',
  'name': 'Neal H. Moritz',
  'profile_path': '/cNcsEYmoS4niCz3UkVAA09dUIob.jpg'},
 {'credit_id': '52fe4cc8c3a36847f823e68d',
  'department': 'Writing',
  'gender': 2,
  'id': 58191,
  'job': 'Writer',
  'name': 'Chris Morgan',
  'profile_path': '/dUGxIwFBLrSFLImxjeda1krndMO.jpg'}]

In [58]:
#getting the producer and director name
producer_list=[]
director_list=[]
for elem in crew_list:
  if elem['job']=='Producer':
    producer_list.append(elem['name'])
  if elem['job']=='Director':
    director_list.append(elem['name'])

In [59]:
print(f'PRODUCERS : {producer_list}')
print(f'DIRECTORS : {director_list}')

PRODUCERS : ['Vin Diesel', 'Neal H. Moritz', 'Michael Fottrell', 'Brandon Birtell']
DIRECTORS : ['James Wan']

In [ ]:
#get the actors for this movie

In [61]:
cast_list =max_profit_movie_df['cast']

In [62]:
actor_list=[]
for elem in cast_list:
  actor_list.append(elem['name'])

In [63]:
#actors
print(f'Actors of the movie are :')
actor_list

Actors of the movie are :

['Vin Diesel',
 'Paul Walker',
 'Dwayne Johnson',
 'Michelle Rodriguez',
 'Tyrese Gibson',
 'Ludacris',
 'Jordana Brewster',
 'Djimon Hounsou',
 'Tony Jaa',
 'Ronda Rousey',
 'Nathalie Emmanuel',
 'Kurt Russell',
 'Jason Statham',
 'Sung Kang',
 'Gal Gadot',
 'Lucas Black',
 'Elsa Pataky',
 'Noel Gugliemi',
 'John Brotherton',
 'Luke Evans',
 'Ali Fazal',
 'Miller Kimsey',
 'Charlie Kimsey',
 'Eden Estrella',
 'Gentry White',
 'Iggy Azalea',
 'Jon Lee Brody',
 'Levy Tran',
 'Anna Colwell',
 'Viktor Hernandez',
 'Steve Coulter',
 'Robert Pralgo',
 'Antwan Mills',
 'J.J. Phillips',
 'Jorge Ferragut',
 'Sara Sohn',
 'Benjamin Blankenship',
 'D.J. Hapa',
 'T-Pain',
 'Brian Mahoney',
 'Brittney Alger',
 'Romeo Santos',
 'Jocelin Donahue',
 'Stephanie Langston',
 'Jorge-Luis Pallo',
 'Tego Calder√≥n',
 'Nathalie Kelley',
 'Shad Moss',
 'Don Omar',
 'Klement Tinaj',
 'Caleb Walker',
 'Cody Walker']

#Q2.This data has information about movies made in different languages. Which language has the highest average ROI (return on investment)?

In [66]:
 #we already calculated roi above
 #df['roi'] = 100 * df['profit']/df['budget']
 #Use groupby function on movie languages and ROI and finding mean
imdb_df_new.groupby('original_language')['roi'].mean().reset_index().sort_values(by='roi',ascending=False).head(5)

   original_language           roi
18                ko  11309.685605
6                 el   5198.013245
28                sr   3261.413600
7                 en    952.119148
32                tr    878.917604

In [67]:
print('Language with highest average roi is')
imdb_df_new.groupby('original_language')['roi'].mean().reset_index().sort_values(by='roi',ascending=False).iloc[0,0]

Language with highest average roi is

'ko'

#Q3.Find out the unique genres of movies in this dataset.

In [68]:
#considering only those rows in genres column which have no null values
no_na_genres = imdb_df_new[~imdb_df_new['genres'].isna()]

In [69]:
len(no_na_genres)

2993

In [75]:
no_na_genres.loc[0,'genres']

[{'id': 35, 'name': 'Comedy'}]

In [74]:
no_na_genres.loc[5,'genres']

[{'id': 16, 'name': 'Animation'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 10751, 'name': 'Family'}]

In [77]:
#particular movie has multiple genres
#create a list of genres and using .iterrow() method to iterate over genres column
# .iterrow() --->> same as enumerate() its compulsory to use it in case of DataFrame

#create list of genres
gen_list=[]

#iterate over each observation in data frame
for index,row in no_na_genres.iterrows():

  genre = no_na_genres.loc[index,'genres']
  for k in genre:
    gen_list.append(k['name'])

#unique list of genres are:
pd.DataFrame(set(gen_list),columns=['Unique Genres'])

      Unique Genres
0               War
1         Animation
2          Thriller
3            Comedy
4   Science Fiction
5             Music
6           Romance
7          TV Movie
8            Horror
9            Family
10          History
11            Drama
12          Western
13            Crime
14           Action
15          Fantasy
16          Foreign
17          Mystery
18        Adventure
19      Documentary

#Q4.Make a table of all the producers and directors of each movie. Find the top 3 producers who have produced movies with the highest average RoI?

In [79]:
#considering only those rows in crew column which have no null values
no_na_crew = imdb_df_new[~imdb_df_new['crew'].isna()]

In [80]:
no_na_crew.shape

(2984, 10)

In [146]:
# Functions
def create_producer_list(row):
    crew_list = row['crew']
    return [elem['name'] for elem in crew_list if elem['job'] == 'Producer']

def create_director(row):
    crew_list = row['crew']
    for elem in crew_list:
        if elem['job'] == 'Director':
            return elem['name']
    return None

In [147]:
rows = []
for index, row in no_na_crew.iterrows():
    try:
        rows.append({
            'Movie Title': row['original_title'],
            'Producers': create_producer_list(row),
            'Directors': create_director(row),
            'ROI': row['roi']
        })
    except Exception as e:
        continue

In [148]:
Table = pd.DataFrame(rows, columns=['Movie Title','Producers','Directors','ROI'])

In [149]:
Table.head(10)

,Movie Title,Producers,Directors,ROI
0,Hot Tub Time Machine 2,[Andrew Panay],Steve Pink,-12.038207
1,The Princess Diaries 2: Royal Engagement,"[Whitney Houston, Mario Iscovich, Debra Martin...",Garry Marshall,137.873588
2,Whiplash,"[David Lancaster, Michel Litvak, Jason Blum, H...",Damien Chazelle,296.727273
3,Kahaani,[Sujoy Ghosh],Sujoy Ghosh,1233.333333
4,마린보이,[],Jong-seok Yoon,-50.950375
5,Pinocchio and the Emperor of the Night,[],Hal Sutherland,-59.229525
6,The Possession,[],Ole Bornedal,510.329107
7,Control Room,[],Jehane Noujaim,-67.668613
8,Muppet Treasure Island,"[Frank Oz, Brian Henson]",Brian Henson,329.092387
9,A Mighty Wind,[Karen Murphy],Christopher Guest,212.504100

#Q5.Which actor has acted in the most number of movies?

In [150]:
#considering only those rows in cast column which have no null values
no_na_cast = imdb_df_new[~imdb_df_new['cast'].isna()]

In [151]:
no_na_cast.loc[0,'cast'][0]['name']

'Rob Corddry'

In [152]:
actor_list=[]
for index,row in no_na_cast.iterrows():
  for iter in no_na_cast.loc[index,'cast']:
    if type(iter)== dict:
      actor= iter['name']
      actor_list.append(actor)

In [153]:
#create a  DataFrame with actor list
Actor_Table = pd.DataFrame(actor_list,columns=['Name of Actor'])

In [154]:
Actor_Table.shape

(61811, 1)

In [156]:
Actor_Table.head()

    Name of Actor
0     Rob Corddry
1  Craig Robinson
2      Clark Duke
3      Adam Scott
4     Chevy Chase

In [157]:
#sorting the actors using groupby function
Actor_Table.value_counts().reset_index().head()

       Name of Actor  count
0  Samuel L. Jackson     30
1     Robert De Niro     30
2     Morgan Freeman     27
3       Bruce Willis     25
4     Susan Sarandon     25

In [158]:
print('Samuel L. Jackson and Robert De Niro both have done 30 films')

Samuel L. Jackson and Robert De Niro both have done 30 films